In [ ]:
#import libraries
import numpy as np
import pandas as pd

In [ ]:
#read the data
movies = pd.read_csv('/content/drive/MyDrive/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/drive/MyDrive/tmdb_5000_credits.csv')

In [ ]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [ ]:
credits.head(1)['crew'].values

array(['[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "depart

In [ ]:
#merging the datasets
movies = movies.merge(credits, on='title')

In [ ]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
#remove unnecessary columns
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
#checking missing data
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
#removing missing data
movies.dropna(inplace = True)

In [ ]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
#check for duplicate data
movies.duplicated().sum()

0

DATA PREPROCESSING

In [ ]:
#preprocess genres and keywords
import ast
def convert(obj):
  res = []
  for i in ast.literal_eval(obj):
    res.append(i['name'])
  return res

In [ ]:
movies['genres'] = movies['genres'].apply(convert)

In [ ]:
movies['keywords'] = movies['keywords'].apply(convert)

In [ ]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
#preprocess the cast
def first10(obj):
  count = 0
  res = []
  for i in ast.literal_eval(obj):
    res.append(i['name'])
    count += 1
    if count == 10:
      return res

  return res

In [ ]:
movies['cast'] = movies['cast'].apply(first10)

In [ ]:
movies['cast'][0]

['Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'Stephen Lang',
 'Michelle Rodriguez',
 'Giovanni Ribisi',
 'Joel David Moore',
 'CCH Pounder',
 'Wes Studi',
 'Laz Alonso']

In [ ]:
#preprocess the crew
def fetch_director(obj):
  res = []
  crew_positions = ['Director', 'Producer', 'Executive Producer']
  for i in ast.literal_eval(obj):
    if i['job'] in crew_positions:
      res.append(i['name'])
  return res

In [ ]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[James Cameron, James Cameron, Jon Landau, Lae..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Gore Verbinski, Jerry Bruckheimer, Mike Stens..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[Sam Mendes, Barbara Broccoli, Callum McDougal..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[Charles Roven, Christopher Nolan, Christopher..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[Andrew Stanton, Colin Wilson, Jim Morris, Lin..."

In [ ]:
#preprocess the overview
movies['overview'] = movies['overview'].apply(lambda x: x.split())
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[James Cameron, James Cameron, Jon Landau, Lae..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Gore Verbinski, Jerry Bruckheimer, Mike Stens..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[Sam Mendes, Barbara Broccoli, Callum McDougal..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[Charles Roven, Christopher Nolan, Christopher..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[Andrew Stanton, Colin Wilson, Jim Morris, Lin..."

In [ ]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ","") for i in x])
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[James Cameron, James Cameron, Jon Landau, Lae..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Gore Verbinski, Jerry Bruckheimer, Mike Stens..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[Sam Mendes, Barbara Broccoli, Callum McDougal..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[Charles Roven, Christopher Nolan, Christopher..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[Andrew Stanton, Colin Wilson, Jim Morris, Lin..."

In [ ]:
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ","") for i in x])

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[JamesCameron, JamesCameron, JonLandau, LaetaK..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[GoreVerbinski, JerryBruckheimer, MikeStenson,..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...","[SamMendes, BarbaraBroccoli, CallumMcDougall, ..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[CharlesRoven, ChristopherNolan, ChristopherNo..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...","[AndrewStanton, ColinWilson, JimMorris, Lindse..."

In [ ]:
#concatenate the columns into one column
movies['tags'] = movies['overview'] + movies['genres'] + movies['cast'] + movies['crew'] + movies['keywords']

In [ ]:
new_df = movies[['movie_id', 'title','tags']]

In [ ]:
#converting a list to a string
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [ ]:
#convert the tags in the string into lowercase
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

MODEL BUILDING

In [ ]:
#Vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [ ]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
print(stop)

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
print(vectors)

In [ ]:
cv.get_feature_names()

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
#stemming
def stem(text):
  Y = []
  for i in text.split():
    #after stemming append it to list y
    Y.append(ps.stem(i))
  return " ".join(Y)

In [ ]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [ ]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-130-be18a4346d89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [ ]:
len(list(new_df['tags'][0]))

549

In [ ]:
#calculate cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [ ]:
similarity

array([[1.        , 0.07317073, 0.05279637, ..., 0.02354408, 0.02602896,
        0.        ],
       [0.07317073, 1.        , 0.05279637, ..., 0.02354408, 0.        ,
        0.        ],
       [0.05279637, 0.05279637, 1.        , ..., 0.02548236, 0.        ,
        0.        ],
       ...,
       [0.02354408, 0.02354408, 0.02548236, ..., 1.        , 0.07537784,
        0.05096472],
       [0.02602896, 0.        , 0.        , ..., 0.07537784, 1.        ,
        0.05634362],
       [0.        , 0.        , 0.        , ..., 0.05096472, 0.05634362,
        1.        ]])

In [ ]:
similarity.shape

(4806, 4806)

In [ ]:
sorted(list(enumerate(similarity[0])),reverse=True)

In [ ]:
sorted(list(enumerate(similarity[0])),reverse= True, key = lambda x: x[1])

[(0, 1.0000000000000002),
 (1216, 0.2344101868269667),
 (2409, 0.23281009858985943),
 (507, 0.22956556456066257),
 (539, 0.228012566372163),
 (1920, 0.228012566372163),
 (582, 0.2254174086668581),
 (260, 0.21749089913081476),
 (1444, 0.216574040912105),
 (74, 0.21189672420660502),
 (1194, 0.2103895814224009),
 (4192, 0.20952908873087345),
 (3608, 0.2068572009460303),
 (83, 0.2050225600506816),
 (3730, 0.2044794529772991),
 (322, 0.19754591932991794),
 (2333, 0.19681830757831292),
 (1537, 0.19325517063098144),
 (1204, 0.19053020329181639),
 (973, 0.19030453673946293),
 (2971, 0.18782637100417848),
 (2204, 0.18748505440195304),
 (972, 0.18478728707195913),
 (3538, 0.18478728707195913),
 (3327, 0.1840525434580776),
 (495, 0.18376916754950667),
 (47, 0.18278756253377793),
 (942, 0.18220272220337375),
 (2786, 0.1803339269334865),
 (4405, 0.1803339269334865),
 (4048, 0.17996401079640129),
 (1321, 0.17914359097500465),
 (279, 0.17848429930126408),
 (1329, 0.17708440083028656),
 (305, 0.17433873995086346),
 (466, 0.17400443716972247),
 (3162, 0.173259232729684),
 (184, 0.1728526794136782),
 (61, 0.1710797845536603),
 (27, 0.16846772605706456),
 (931, 0.16829781403596433),
 (1201, 0.16829781403596433),
 (838, 0.16680974049047873),
 (300, 0.16671392788033934),
 (2731, 0.16648178955300671),
 (1344, 0.1656472891122698),
 (36, 0.1648085632718039),
 (150, 0.16450880628040013),
 (1275, 0.16311817434811104),
 (1071, 0.16118595467047642),
 (4, 0.15946199115053014),
 (151, 0.15939417826583457),
 (461, 0.15939417826583457),
 (581, 0.15939417826583457),
 (301, 0.15813828894867524),
 (67, 0.15617376188860607),
 (220, 0.15617376188860607),
 (373, 0.15617376188860607),
 (2999, 0.15617376188860607),
 (4010, 0.15617376188860607),
 (2496, 0.15314097295792223),
 (1831, 0.1530809058942434),
 (661, 0.15151080381571405),
 (3354, 0.15027827244457206),
 (158, 0.15016481204905047),
 (1396, 0.15016481204905047),
 (1945, 0.1500468969841066),
 (1808, 0.14815943949743846),
 (3628, 0.1475703340252388),
 (108, 0.14740926029993148),
 (149, 0.14724203476646208),
 (1383, 0.14634146341463417),
 (4336, 0.14634146341463417),
 (7, 0.14354633705913583),
 (1965, 0.14354633705913583),
 (26, 0.1428976524688623),
 (1297, 0.1428976524688623),
 (3443, 0.1428976524688623),
 (56, 0.14256648712805026),
 (2515, 0.14256648712805026),
 (2169, 0.1402481783633036),
 (168, 0.13968605915391566),
 (208, 0.13968605915391563),
 (502, 0.13815938971755123),
 (1938, 0.13815938971755123),
 (46, 0.1381593897175512),
 (1355, 0.1381593897175512),
 (311, 0.1366817067004544),
 (1488, 0.1363196353181994),
 (740, 0.13525044520011487),
 (84, 0.13456562841903869),
 (91, 0.13391789600139503),
 (2686, 0.13391789600139503),
 (41, 0.13386322447594806),
 (1327, 0.13318543164240537),
 (3999, 0.13318543164240537),
 (577, 0.13199091933711365),
 (17, 0.1316077808820154),
 (2584, 0.13025792180516724),
 (1299, 0.1301448015738384),
 (4348, 0.129944424547263),
 (1322, 0.12871269604204325),
 (2133, 0.12871269604204325),
 (1178, 0.1283740414907742),
 (172, 0.12751534261266767),
 (490, 0.12751534261266767),
 (1833, 0.12751534261266767),
 (2620, 0.12751534261266767),
 (31, 0.126673647984535),
 (282, 0.126673647984535),
 (3622, 0.126673647984535),
 (2873, 0.1263507945427984),
 (2480, 0.12521758066945232),
 (94, 0.12503908082008883),
 (111, 0.12503908082008883),
 (332, 0.12503908082008883),
 (3409, 0.12503908082008883),
 (2970, 0.12493900951088487),
 (4490, 0.12493900951088487),
 (595, 0.12346619958119871),
 (1037, 0.12346619958119871),
 (3675, 0.12346619958119871),
 (199, 0.1230397174792593),
 (342, 0.12299644696008073),
 (505, 0.12251277836633778),
 (1658, 0.12251277836633778),
 (1747, 0.12251277836633778),
 (2378, 0.12251277836633778),
 (127, 0.12222530175967619),
 (557, 0.12195121951219512),
 (568, 0.12195121951219512),
 (587, 0.12195121951219512),
 (1673, 0.12097167578182677),
 (1715, 0.12097167578182677),
 (187, 0.12049067317796996),
 (249, 0.12022261795565765),
 (368, 0.12022261795565765),
 (487, 0.12022261795565765),
 (1015, 0.11908137705738525),
 (1479, 0.11908137705738525),
 (1220, 0.11908137705738524),
 (3407, 0.11908137705738524),
 (1741, 0.1190045255637029),
 (157, 0.11805626722019105),
 (422, 0.11805626722019105),
 (1047, 0.11805626722019105),
 (413, 0.11772040233700279),
 (454, 0.11772040233700279),
 (1617, 0.11772040233700279),
 (1002, 0.11713032141645455),
 (52, 0.11640504929492972),
 (123, 0.11640504929492972),
 (228, 0.11640504929492972),
 (939, 0.11622582663390896),
 (3376, 0.11600295811314831),
 (2713, 0.11513282476462602),
 (238, 0.11447797027778953),
 (2075, 0.1140531897024402),
 (2868, 0.1140531897024402),
 (4673, 0.1140531897024402),
 (4203, 0.11363310286178555),
 (3309, 0.11270870433342906),
 (3630, 0.11270870433342906),
 (3147, 0.11199800894198361),
 (420, 0.11155268706329005),
 (432, 0.11155268706329005),
 (1277, 0.11155268706329005),
 (1373, 0.11043152607484656),
 (4018, 0.11043152607484656),
 (549, 0.11043152607484655),
 (692, 0.11043152607484655),
 (778, 0.11043152607484655),
 (1512, 0.11043152607484655),
 (68, 0.11043152607484653),
 (1982, 0.11043152607484653),
 (206, 0.10934350421017384),
 (87, 0.10874544956540738),
 (294, 0.10874544956540738),
 (1031, 0.10874544956540738),
 (2547, 0.1082870204560525),
 (95, 0.10828702045605249),
 (81, 0.1074861545850028),
 (627, 0.10748615458500278),
 (4000, 0.10748615458500278),
 (4545, 0.10726058003503604),
 (134, 0.10713431680111603),
 (579, 0.10713431680111603),
 (1158, 0.10713431680111603),
 (50, 0.10559273546969093),
 (72, 0.10559273546969093),
 (1096, 0.10559273546969093),
 (1274, 0.10559273546969093),
 (2450, 0.10559273546969093),
 (3498, 0.10559273546969093),
 (4079, 0.10559273546969093),
 (102, 0.10529232878566533),
 (3781, 0.10476454436543674),
 (141, 0.10476454436543672),
 (2323, 0.10476454436543672),
 (3721, 0.10476454436543672),
 (4198, 0.10476454436543672),
 (1019, 0.10434798389121028),
 (2439, 0.10434798389121028),
 (275, 0.10411584125907071),
 (687, 0.10411584125907071),
 (859, 0.10411584125907071),
 (2013, 0.10411584125907071),
 (2583, 0.10411584125907071),
 (3140, 0.10411584125907071),
 (169, 0.10342860047301516),
 (777, 0.10342860047301516),
 (28, 0.10269923319261937),
 (483, 0.10269923319261937),
 (3102, 0.10269923319261937),
 (3340, 0.10269923319261937),
 (2106, 0.10253309789938275),
 (2760, 0.10253309789938275),
 (25, 0.10223972648864957),
 (1574, 0.10223972648864957),
 (3055, 0.10223972648864955),
 (3839, 0.10223972648864955),
 (1082, 0.101338918387628),
 (1273, 0.101338918387628),
 (5, 0.10080972981818898),
 (131, 0.10003126465607107),
 (166, 0.10003126465607107),
 (232, 0.10003126465607107),
 (900, 0.10003126465607107),
 (1109, 0.10003126465607107),
 (1294, 0.10003126465607107),
 (3620, 0.10003126465607107),
 (4230, 0.10003126465607107),
 (773, 0.09988907373180403),
 (808, 0.09988907373180403),
 (1156, 0.09988907373180403),
 (1524, 0.09988907373180403),
 (1721, 0.09988907373180403),
 (2259, 0.09988907373180403),
 (4331, 0.09988907373180403),
 (4623, 0.09988907373180403),
 (239, 0.09917043796975242),
 (513, 0.09877295966495897),
 (535, 0.09877295966495897),
 (754, 0.09877295966495897),
 (1195, 0.09877295966495897),
 (3008, 0.09877295966495897),
 (4097, 0.09877295966495897),
 (18, 0.09838022268349253),
 (1727, 0.09769344135387543),
 (653, 0.09769344135387542),
 (1575, 0.09769344135387542),
 (2651, 0.09769344135387542),
 (4135, 0.09769344135387542),
 (14, 0.0975609756097561),
 (1086, 0.0975609756097561),
 (2072, 0.0975609756097561),
 (2181, 0.0975609756097561),
 (10, 0.09639253854237598),
 (854, 0.09639253854237598),
 (870, 0.09639253854237598),
 (2596, 0.09639253854237598),
 (1301, 0.09563650695950075),
 (1306, 0.09563650695950075),
 (1501, 0.09563650695950075),
 (1589, 0.09563650695950075),
 (1942, 0.09563650695950075),
 (1948, 0.09563650695950075),
 (2456, 0.09563650695950075),
 (2634, 0.09563650695950075),
 (2661, 0.09563650695950075),
 (3736, 0.09563650695950075),
 (3954, 0.09563650695950075),
 (174, 0.09526510164590819),
 (295, 0.09526510164590819),
 (508, 0.09526510164590819),
 (813, 0.09526510164590819),
 (988, 0.09526510164590819),
 (1056, 0.09526510164590819),
 (3783, 0.09526510164590819),
 (85, 0.09514225813685229),
 (403, 0.09469425238482128),
 (126, 0.09417632186960223),
 (1823, 0.09417632186960223),
 (2388, 0.09417632186960223),
 (3464, 0.09417632186960223),
 (139, 0.09400555777286816),
 (325, 0.09370425713316365),
 (3093, 0.09370425713316365),
 (4256, 0.09370425713316365),
 (307, 0.09323922072849748),
 (412, 0.09312403943594377),
 (529, 0.09312403943594377),
 (898, 0.09312403943594377),
 (1233, 0.09312403943594377),
 (1439, 0.09312403943594377),
 (1846, 0.09312403943594377),
 (1089, 0.09267207805026595),
 (278, 0.09210625981170081),
 (330, 0.09210625981170081),
 (510, 0.09210625981170081),
 (1401, 0.09210625981170081),
 (1924, 0.09210625981170081),
 (785, 0.0920262717290388),
 (233, 0.09188458377475334),
 (1280, 0.09188458377475334),
 (1408, 0.09188458377475334),
 (1686, 0.09188458377475334),
 (2521, 0.09188458377475334),
 (2762, 0.09188458377475334),
 (266, 0.09112113780030294),
 (334, 0.09112113780030294),
 (371, 0.09112113780030294),
 (410, 0.09112113780030294),
 (1202, 0.09112113780030294),
 (1357, 0.09112113780030294),
 (4045, 0.09112113780030294),
 (129, 0.09016696346674324),
 (182, 0.09016696346674324),
 (263, 0.09016696346674324),
 (400, 0.09016696346674324),
 (476, 0.09016696346674324),
 (715, 0.09016696346674324),
 (1474, 0.09016696346674324),
 (2652, 0.09016696346674324),
 (2796, 0.09016696346674324),
 (3297, 0.09016696346674324),
 (3663, 0.09016696346674324),
 (4468, 0.09016696346674324),
 (4654, 0.09016696346674324),
 (479, 0.09016696346674322),
 (596, 0.08924214965063204),
 (618, 0.08924214965063204),
 (2284, 0.08924214965063204),
 (794, 0.0885422004151433),
 (935, 0.0885422004151433),
 (980, 0.0885422004151433),
 (1077, 0.0885422004151433),
 (1756, 0.0885422004151433),
 (2093, 0.0885422004151433),
 (2396, 0.0885422004151433),
 (2562, 0.0885422004151433),
 (2660, 0.0885422004151433),
 (589, 0.08834522085987724),
 (643, 0.08834522085987724),
 (933, 0.08834522085987724),
 (1496, 0.08747480336813908),
 (1832, 0.08747480336813908),
 (660, 0.08700221858486124),
 (786, 0.08700221858486124),
 (791, 0.08700221858486124),
 (2247, 0.08700221858486124),
 (4626, 0.08700221858486124),
 (160, 0.0867632010492256),
 (2448, 0.0867632010492256),
 (270, 0.086629616364842),
 (467, 0.086629616364842),
 (2274, 0.086629616364842),
 (4353, 0.086629616364842),
 (4516, 0.086629616364842),
 (43, 0.08580846402802883),
 (1278, 0.08580846402802883),
 (2003, 0.08580846402802883),
 (142, 0.08553989227683015),
 (148, 0.08553989227683015),
 (369, 0.08553989227683015),
 (530, 0.08553989227683015),
 (624, 0.08553989227683015),
 (781, 0.08553989227683015),
 (901, 0.08553989227683015),
 (920, 0.08553989227683015),
 (1586, 0.08553989227683015),
 (3537, 0.08553989227683015),
 (3816, 0.08553989227683015),
 (4259, 0.08553989227683015),
 (473, 0.0850102284084451),
 (1418, 0.0850102284084451),
 (2488, 0.0850102284084451),
 (2498, 0.0850102284084451),
 (243, 0.08423386302853227),
 (2005, 0.08423386302853227),
 (2968, 0.08423386302853227),
 (33, 0.08414890701798217),
 (35, 0.08414890701798217),
 (1004, 0.08414890701798217),
 (1249, 0.08414890701798217),
 (1790, 0.08414890701798217),
 (2817, 0.08414890701798217),
 (2840, 0.08414890701798217),
 (812, 0.08347838711296822),
 (1276, 0.08347838711296822),
 (1497, 0.08347838711296822),
 (2856, 0.08347838711296822),
 (3154, 0.08347838711296822),
 (4737, 0.08347838711296822),
 (105, 0.0828236445561349),
 (511, 0.0828236445561349),
 (626, 0.0828236445561349),
 (937, 0.0828236445561349),
 (960, 0.0828236445561349),
 (1560, 0.0828236445561349),
 (2167, 0.0828236445561349),
 (3428, 0.0828236445561349),
 (4657, 0.0828236445561349),
 (222, 0.08274288037841213),
 (1878, 0.08274288037841213),
 (3441, 0.08274288037841213),
 (19, 0.0820264783195062),
 (170, 0.0820264783195062),
 (1828, 0.0820264783195062),
 (292, 0.08155908717405554),
 (691, 0.08155908717405554),
 (1181, 0.08155908717405554),
 (1378, 0.08155908717405554),
 (1523, 0.08155908717405554),
 (2253, 0.08155908717405554),
 (3235, 0.08155908717405554),
 (3310, 0.08155908717405554),
 (3910, 0.08155908717405554),
 (2386, 0.08141120112822953),
 (1282, 0.08132836793622449),
 (3431, 0.08132836793622449),
 (799, 0.08097232353140799),
 (45, 0.08064778385455118),
 (107, 0.08064778385455118),
 (2099, 0.08064778385455118),
 (3218, 0.08064778385455118),
 (3253, 0.08064778385455118),
 (4492, 0.08064778385455118),
 (4502, 0.08064778385455118),
 (4718, 0.08064778385455118),
 (12, 0.08035073760083702),
 (88, 0.08035073760083702),
 (122, 0.08035073760083702),
 (164, 0.08035073760083702),
 (543, 0.08035073760083702),
 (775, 0.08035073760083702),
 (814, 0.08035073760083702),
 (922, 0.08035073760083702),
 (1269, 0.08035073760083702),
 (1473, 0.08035073760083702),
 (1614, 0.08035073760083702),
 (1616, 0.08035073760083702),
 (2644, 0.08035073760083702),
 (2794, 0.08035073760083702),
 (3423, 0.08035073760083702),
 (32, 0.07998400479840057),
 (103, 0.07998400479840057),
 (230, 0.07998400479840057),
 (607, 0.07998400479840057),
 (1639, 0.07998400479840057),
 (1898, 0.07998400479840057),
 (2203, 0.07998400479840057),
 (2763, 0.07933635037580193),
 (39, 0.0791945516022682),
 (75, 0.0791945516022682),
 (207, 0.0791945516022682),
 (227, 0.0791945516022682),
 (241, 0.0791945516022682),
 (245, 0.0791945516022682),
 (306, 0.0791945516022682),
 (315, 0.0791945516022682),
 (389, 0.0791945516022682),
 (1142, 0.0791945516022682),
 (1700, 0.0791945516022682),
 (2251, 0.0791945516022682),
 (2304, 0.0791945516022682),
 (3449, 0.0791945516022682),
 (63, 0.07870417814679402),
 (501, 0.07870417814679402),
 (23, 0.07808688094430304),
 (37, 0.07808688094430304),
 (112, 0.07808688094430304),
 (544, 0.07808688094430304),
 (894, 0.07808688094430304),
 (987, 0.07808688094430304),
 (1027, 0.07808688094430304),
 (2801, 0.07808688094430304),
 (3155, 0.07808688094430304),
 (3527, 0.07808688094430304),
 (4061, 0.07808688094430304),
 (4431, 0.07808688094430304),
 (4641, 0.07808688094430304),
 (363, 0.07748388442260598),
 (491, 0.07748388442260598),
 (125, 0.07731753330571375),
 (138, 0.07702442489446452),
 (203, 0.07702442489446452),
 (236, 0.07702442489446452),
 (242, 0.07702442489446452),
 (349, 0.07702442489446452),
 (356, 0.07702442489446452),
 (1842, 0.07702442489446452),
 (2235, 0.07702442489446452),
 (2820, 0.07702442489446452),
 (51, 0.07631864685185968),
 (572, 0.07631864685185968),
 (1405, 0.07631864685185968),
 (86, 0.076004188790721),
 (503, 0.076004188790721),
 (564, 0.076004188790721),
 (680, 0.076004188790721),
 (752, 0.076004188790721),
 (1113, 0.076004188790721),
 (1290, 0.076004188790721),
 (2683, 0.076004188790721),
 (3091, 0.076004188790721),
 (3206, 0.076004188790721),
 (3301, 0.076004188790721),
 (3389, 0.076004188790721),
 (4083, 0.076004188790721),
 (153, 0.07575540190785703),
 (193, 0.07575540190785703),
 (1139, 0.07575540190785703),
 (2410, 0.07575540190785703),
 (2880, 0.07575540190785703),
 (3069, 0.07575540190785703),
 (4099, 0.07575540190785703),
 (4165, 0.07575540190785703),
 (274, 0.07548943712462224),
 (654, 0.07520444621829453),
 (21, 0.07502344849205331),
 (96, 0.07502344849205331),
 (101, 0.07502344849205331),
 (1011, 0.07502344849205331),
 (1207, 0.07502344849205331),
 (3355, 0.07502344849205331),
 (3470, 0.07502344849205331),
 (3701, 0.07502344849205331),
 (4055, 0.07502344849205331),
 (4451, 0.07502344849205331),
 (415, 0.07466533929465574),
 (1534, 0.07466533929465574),
 (11, 0.07407971974871923),
 (82, 0.07407971974871923),
 (98, 0.07407971974871923),
 (471, 0.07407971974871923),
 (746, 0.07407971974871923),
 (885, 0.07407971974871923),
 (899, 0.07407971974871923),
 (1032, 0.07407971974871923),
 (2018, 0.07407971974871923),
 (3028, 0.07407971974871923),
 (4123, 0.07407971974871923),
 (313, 0.07362101738323104),
 (381, 0.07362101738323104),
 (2250, 0.07362101738323104),
 (2326, 0.07362101738323104),
 (2712, 0.07362101738323104),
 (2789, 0.07362101738323104),
 (3398, 0.07362101738323104),
 (3832, 0.07362101738323104),
 (3982, 0.07362101738323104),
 (4568, 0.07362101738323104),
 (1, 0.07317073170731708),
 (71, 0.07317073170731708),
 (97, 0.07317073170731708),
 (121, 0.07317073170731708),
 (1367, 0.07317073170731708),
 (2395, 0.07317073170731708),
 (2650, 0.07317073170731708),
 (3907, 0.07317073170731708),
 (4640, 0.07317073170731708),
 (1926, 0.07261932421315972),
 (70, 0.07229440390678199),
 (362, 0.07229440390678199),
 (632, 0.07229440390678199),
 (787, 0.07229440390678199),
 (827, 0.07229440390678199),
 (1765, 0.07229440390678199),
 (2052, 0.07229440390678199),
 (2701, 0.07229440390678199),
 (3022, 0.07229440390678199),
 (55, 0.07213357077339458),
 (59, 0.07213357077339458),
 (190, 0.07165743639000186),
 (1288, 0.07165743639000186),
 (1664, 0.07165743639000186),
 (1770, 0.07165743639000186),
 (2165, 0.07165743639000186),
 (2882, 0.07165743639000186),
 (3994, 0.07165743639000186),
 (4412, 0.07165743639000186),
 (212, 0.07144882623443115),
 (223, 0.07144882623443115),
 (254, 0.07144882623443115),
 (457, 0.07144882623443115),
 (472, 0.07144882623443115),
 (1175, 0.07144882623443115),
 (1446, 0.07144882623443115),
 (2163, 0.07144882623443115),
 (2354, 0.07144882623443115),
 (2363, 0.07144882623443115),
 (229, 0.07119060773078313),
 (257, 0.07063224140220167),
 (312, 0.07063224140220167),
 (536, 0.07063224140220167),
 (547, 0.07063224140220167),
 (1146, 0.07063224140220167),
 (1161, 0.07063224140220167),
 (2592, 0.07063224140220167),
 (2916, 0.07063224140220167),
 (3822, 0.07063224140220167),
 (4181, 0.07063224140220167),
 (979, 0.06984302957695783),
 (1701, 0.06984302957695783),
 (1883, 0.06984302957695783),
 (2021, 0.06984302957695783),
 (2264, 0.06984302957695783),
 (3188, 0.06984302957695783),
 (1005, 0.06984302957695782),
 (1323, 0.06984302957695782),
 (1655, 0.06984302957695782),
 (2339, 0.06984302957695782),
 (3072, 0.06984302957695782),
 (4006, 0.06984302957695782),
 (4403, 0.06984302957695782),
 (665, 0.0690796948587756),
 (908, 0.0690796948587756),
 (1289, 0.0690796948587756),
 (1340, 0.0690796948587756),
 (1632, 0.0690796948587756),
 (4538, 0.0690796948587756),
 (488, 0.0685691896140358),
 (1990, 0.0685691896140358),
 (76, 0.0683408533502272),
 (271, 0.0683408533502272),
 (365, 0.0683408533502272),
 (635, 0.0683408533502272),
 (737, 0.0683408533502272),
 (1623, 0.0683408533502272),
 (1996, 0.0683408533502272),
 (2056, 0.0683408533502272),
 (2135, 0.0683408533502272),
 (3000, 0.0683408533502272),
 (109, 0.0681598176590997),
 (256, 0.0681598176590997),
 (800, 0.0681598176590997),
 (1348, 0.0681598176590997),
 (1621, 0.0681598176590997),
 (2622, 0.0681598176590997),
 (2659, 0.0681598176590997),
 (3515, 0.0681598176590997),
 (3671, 0.0681598176590997),
 (3931, 0.0681598176590997),
 (4216, 0.0681598176590997),
 (4443, 0.0681598176590997),
 (4638, 0.0681598176590997),
 (3212, 0.06796590597837962),
 (183, 0.06775769133151423),
 (329, 0.06762522260005743),
 (634, 0.06762522260005743),
 (674, 0.06762522260005743),
 (728, 0.06762522260005743),
 (782, 0.06762522260005743),
 (1191, 0.06762522260005743),
 (1455, 0.06762522260005743),
 (2241, 0.06762522260005743),
 (2372, 0.06762522260005743),
 (2831, 0.06762522260005743),
 (3225, 0.06762522260005743),
 (16, 0.06693161223797403),
 (704, 0.06693161223797403),
 (732, 0.06693161223797403),
 (784, 0.06693161223797403),
 (1325, 0.06693161223797403),
 (2792, 0.06693161223797403),
 (3390, 0.06693161223797403),
 (62, 0.06659271582120269),
 (179, 0.06659271582120269),
 (701, 0.06659271582120269),
 (850, 0.06659271582120269),
 (1262, 0.06659271582120269),
 (2381, 0.06659271582120269),
 (2698, 0.06659271582120269),
 (3621, 0.06659271582120269),
 (3976, 0.06659271582120269),
 (4290, 0.06659271582120269),
 (4320, 0.06659271582120269),
 (4472, 0.06659271582120269),
 (4473, 0.06659271582120269),
 (4591, 0.06659271582120269),
 (1030, 0.06625891564490793),
 (1093, 0.06625891564490793),
 (1168, 0.06625891564490793),

In [ ]:
def recommend(movie):
  movie_index = new_df[new_df['title']==movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:26]
  for i in movies_list:
    print(new_df.iloc[i[0]].title)

In [ ]:
recommend("Harry Potter and the Philosopher's Stone")

Harry Potter and the Chamber of Secrets
Harry Potter and the Goblet of Fire
Harry Potter and the Prisoner of Azkaban
Harry Potter and the Order of the Phoenix
Harry Potter and the Half-Blood Prince
I Love You, Beth Cooper
Percy Jackson & the Olympians: The Lightning Thief
The Wiz
Percy Jackson: Sea of Monsters
Night at the Museum: Secret of the Tomb
Dude Where's My Dog?
The Craft
The NeverEnding Story
Snow Day
The DUFF
Stormbreaker
The Adventures of Pinocchio
Spirited Away
Wish I Was Here
Hocus Pocus
Oz: The Great and Powerful
The Chronicles of Narnia: Prince Caspian
Dumb and Dumberer: When Harry Met Lloyd
Just Visiting
The Indian in the Cupboard

In [ ]:
import pickle
pickle.dump(new_df,open('/content/drive/MyDrive/movies.pkl','wb'))